version: '3'

services:
  vortexnotes:
    container_name: vortexnotes
    image: vortexnotes:latest
    ports:
      - "0.0.0.0:7701:7701"
    volumes:
      - ./app/data/notes:/data/notes
      - ./app/data/vortexnotes:/data/vortexnotes
